server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true

